In [1]:
l_sel= [[5, 0, 1], [4, 2, 1], [5, 1, 0], [1, 5, 4], [0, 1, 4], [2, 1, 0], [1, 5, 3], [3, 2, 5], [0, 5, 3], [0, 4, 5],
        [0, 2, 3], [4, 0, 3], [4, 3, 1], [5, 3, 4], [2, 4, 3], [0, 2, 3], [3, 4, 1], [4, 3, 5], [2, 4, 1], [2, 3, 1],
        [3, 1, 2], [2, 4, 0], [4, 0, 5], [4, 3, 2]]

l_rand= [0.59, 0.96, 0.64, 0.86, 0.44, 0.70, 0.78, 0.96, 0.67, 0.89, 0.46, 0.34, 0.24, 0.80, 0.77, 0.11, 0.91, 0.69,
         0.80, 0.50, 0.60, 0.18, 0.55, 0.39, 0.68, 0.21, 0.01, 0.91, 0.78, 0.35, 0.04, 0.49, 0.43, 0.13, 0.82, 0.66,
         0.40, 0.50, 0.93, 0.64, 0.75, 0.96, 0.13, 0.30, 0.63, 0.55, 0.46, 0.87, 0.03, 0.59, 0.87, 0.42, 0.34, 0.68,
         0.99, 0.32, 0.15, 0.69, 0.40, 0.49, 0.58, 0.48, 0.76, 0.22, 0.73, 0.50, 0.10, 0.21, 0.95, 0.64, 0.41, 0.13,
         0.69, 0.48, 0.41, 0.08, 0.34, 0.14, 0.62, 0.71, 0.01, 0.70, 0.05, 0.37, 0.96, 0.26, 0.58, 0.88, 0.95, 0.05,
         0.06, 0.51, 0.39, 0.61, 0.45, 0.42, 0.25, 0.69, 0.18, 0.66, 0.72, 0.33, 0.90, 0.78, 0.36, 0.37, 0.91, 0.15, ]

l_cross= [1, 2, 2, 1, 2, 2, 2, 1, 1, 1]

pop=[[0, 1, 0, 1], [1, 0, 1, 0], [0, 0, 0, 0], [0, 1, 0, 1], [1, 0, 0, 1], [0, 0, 0, 1]]

r_cross = 0.9
r_mut = 0.25

min_value = -1
max_value = 1

In [3]:
import numpy as np

In [2]:
f = lambda x: x**2



In [9]:
np.binary_repr(3),np.binary_repr(4),np.binary_repr(-3, width=4),np.binary_repr(3, width=4)

('11', '100', '1101', '0011')

In [10]:
a = 7
b = 2
np.binary_repr(a, width=4),np.binary_repr(b, width=4)

('0111', '0010')

In [23]:
print( np.binary_repr(a, width=4),np.binary_repr(b, width=4),sep='\n' )
print("-"*4)
print(np.binary_repr(a & b, width=4))
print(np.binary_repr(a | b, width=4))
print(np.binary_repr(a ^ b, width=4))
print("-"*4)
print(np.binary_repr(a & ~b, width=4))
print(np.binary_repr(~a & b, width=4))
print("-"*4)
print(np.binary_repr(a << 2 , width=8))
print(np.binary_repr(a << 4 , width=8))
print("-"*4)
print(np.binary_repr(a >> 2 , width=8))
print(np.binary_repr(a >> 4 , width=8))

0111
0010
----
0010
0111
0101
----
0101
0000
----
00011100
01110000
----
00000001
00000000


In [25]:
np.bitwise_and(np.array([2,5,255]), np.array([3,14,16]))

array([ 2,  4, 16])

In [26]:
np.array([7,2,5,255]) & np.array([2,3,14,16])

array([ 2,  2,  4, 16])

In [27]:
print(np.binary_repr(7 & 2, width=4))

0010


In [28]:
np.array([7,2,5,255]) | np.array([2,3,14,16])

array([  7,   3,  15, 255])

In [29]:
np.array([7,2,5,255]) << np.array([2,3,14,16])

array([      28,       16,    81920, 16711680])

In [31]:
np.binary_repr( 7 << 2),7 << 2

('11100', 28)

In [35]:
a = [1,2,3,4]
a *2,type(a)

([1, 2, 3, 4, 1, 2, 3, 4], list)

In [39]:

b= np.array(a)
b,type(b)

(array([1, 2, 3, 4]), numpy.ndarray)

In [59]:
pop=[[0, 1, 0, 1], [1, 0, 1, 0], [0, 0, 0, 0], [0, 1, 0, 1], [1, 0, 0, 1], [0, 0, 0, 1]]

In [60]:
np.packbits(pop)

array([ 90,   5, 145], dtype=uint8)

In [66]:

b = [0, 0, 0, 0]

popn = []
for elem in pop:
    popn.append(b+elem)
popn,np.packbits(popn)

([[0, 0, 0, 0, 0, 1, 0, 1],
  [0, 0, 0, 0, 1, 0, 1, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 1],
  [0, 0, 0, 0, 1, 0, 0, 1],
  [0, 0, 0, 0, 0, 0, 0, 1]],
 array([ 5, 10,  0,  5,  9,  1], dtype=uint8))

In [67]:
choices = [[0, 1, 2, 3], [10, 11, 12, 13],
          [20, 21, 22, 23], [30, 31, 32, 33]]
np.choose([2, 3, 1, 0], choices)

array([20, 31, 12,  3])

In [68]:
np.choose([0,0,1,4],[1,2,3,4,5])

array([1, 1, 2, 5])

In [69]:
[1,4,1,4,4,1]

[1, 4, 1, 4, 4, 1]

In [84]:
torneos = [[5, 0, 1], [4, 2, 1], [5, 1, 0], [1, 5, 4], [0, 1, 4], [2, 1, 0]]
ind_ganador_torneo = [2, 0, 1, 2, 2, 1]

for datos,ind in zip(torneos,ind_ganador_torneo):
    print(datos[ind])

1
4
1
4
4
1


In [88]:
choices = np.array( [[5, 0, 1], [4, 2, 1], [5, 1, 0], [1, 5, 4], [0, 1, 4], [2, 1, 0]])
index_array = np.array( [2, 0, 1, 2, 2, 1] )
#np.choose(index_array, choices)
np.take(choices,index_array)


array([1, 5, 0, 1, 1, 0])

In [96]:
index_array.reshape( (-1,1) )

array([[2],
       [0],
       [1],
       [2],
       [2],
       [1]])

In [97]:
np.take_along_axis(choices,index_array.reshape( (-1,1) ),axis=1)

array([[1],
       [4],
       [1],
       [4],
       [4],
       [1]])

In [73]:
np.take_along_axis?

Signature:       np.take_along_axis(arr, indices, axis)
Call signature:  np.take_along_axis(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function take_along_axis at 0x000001D8E8DFF6A0>
File:            c:\users\michel_gpc\.conda\envs\robotica_2023\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Take values from the input array by matching 1d index and data slices.

This iterates over matching 1d slices oriented along the specified axis in
the index and data arrays, and uses the former to look up values in the
latter. These slices can be different lengths.

Functions returning an index along an axis, like `argsort` and
`argpartition`, produce suitable indices for this function.

.. versionadded:: 1.15.0

Parameters
----------
arr : ndarray (Ni..., M, Nk...)
    Source array
indices : ndarray (Ni..., J, Nk...)
    Indices to take along each 1d slice of `arr`. This must match the
    dimension of arr, but dimensions Ni and Nj only need to broadca

In [98]:
a = [1,2,3,4,5,6]
b = a[0::2]
c = a[1::2]
b,c

([1, 3, 5], [2, 4, 6])

In [4]:
(np.array([10, 10,  9], dtype=np.uint8), np.array([ 9,  9, 10], dtype=np.uint8))

(array([10, 10,  9], dtype=uint8), array([ 9,  9, 10], dtype=uint8))

In [7]:
a = 10
b = 9

print( np.binary_repr(a, width=4),np.binary_repr(b, width=4),sep='\n' )

1010
1001


In [26]:
a = 7
b = 2
print( np.binary_repr(a, width=4),np.binary_repr(b, width=4),sep='\n' )
print("-"*4)
print("&",np.binary_repr(a & b, width=4))
print("|",np.binary_repr(a | b, width=4))
print("^",np.binary_repr(a ^ b, width=4))
print("-"*4)
print("a & ~b",np.binary_repr(a & ~b, width=4))
print("~a & b",np.binary_repr(~a & b, width=4))

print("a & ~a",np.binary_repr(a & ~a, width=4))
print("~a & a",np.binary_repr(~a & a, width=4))
print("-"*4)
print(np.binary_repr(a << 2 , width=8))
print(np.binary_repr(a << 4 , width=8))
print("-"*4)
print(np.binary_repr(a >> 2 , width=8))
print(np.binary_repr(a >> 4 , width=8))

0111
0010
----
& 0010
| 0111
^ 0101
----
a & ~b 0101
~a & b 0000
a & ~a 0000
~a & a 0000
----
00011100
01110000
----
00000001
00000000


In [10]:
a = 7
b = 2
print( np.binary_repr(a, width=4),np.binary_repr(b, width=4),sep='\n' )

0111
0010


In [ ]:
a = '0111'
b = '0010'

ab = '0110'
ba = '0011' 

In [37]:
np.binary_repr( 12, width=4 ),np.binary_repr( 3, width=4 ),

('1100', '0011')

In [32]:
a = 7
b= 2
np.binary_repr( (a <<2 & 15) | b  , width=4)

'1110'

In [35]:
np.binary_repr( (a & 12)  , width=4)

'0100'

In [68]:
a = 7
b= 2

print( np.binary_repr(a, width=4),np.binary_repr(b, width=4),sep='\n' )
print("Mask 12,3", np.binary_repr(12, width=4),np.binary_repr(3, width=4),sep='\n' )


print ("ab:" ,np.binary_repr( (a & 12) | (b & 3)  , width=4))
print ("ba:" ,np.binary_repr( (b & 12) | (a & 3)  , width=4))

0111
0010
Mask 12,3
1100
0011
ab: 0110
ba: 0011


In [64]:
np.binary_repr( -1  , width=14),np.binary_repr( 1 & -1  , width=14)

('11111111111111', '00000000000001')

In [51]:
np.binary_repr( ~( (255>>3)<<3)  , width=8)

C:\Users\Michel_GPC\AppData\Local\Temp\ipykernel_20304\3154595694.py:1: DeprecationWarning: Insufficient bit width provided. This behavior will raise an error in the future.
  np.binary_repr( ~( (255>>3)<<3)  , width=8)


'100000111'

In [76]:
np.binary_repr( ~(-1 << 3)  , width=4),np.binary_repr( -2   , width=4)

('0111', '1110')

In [89]:
#m = 1#,2
m=4
nb = 8
np.binary_repr( (-1 << m), width=nb),np.binary_repr( ~(-1 << m), width=nb)

('11110000', '00001111')

In [91]:
(-1 << m), ~(-1 << m)

(-16, 15)

In [161]:
a = 7
b = 2
nb = 4

valor_de_alla = 1
m=nb-valor_de_alla
m = 4-0 
print( np.binary_repr(a, width=nb),np.binary_repr(b, width=nb),sep='\n' )
print("-"*4)

#print("Mask 12,3", np.binary_repr(12, width=nb),np.binary_repr(3, width=nb),sep='\n' )


mask_a= (-1 << m)
mask_b= ~(-1 << m) # ~mask_a

print("Masks", np.binary_repr(mask_a, width=nb),np.binary_repr(mask_b, width=nb),sep='\n' )


print("*"*8)
print ("ab:" ,np.binary_repr( (a & mask_a) | (b & mask_b)  , width=4))
print ("ba:" ,np.binary_repr( (b & mask_a) | (a & mask_b)  , width=4))

0111
0010
----
Masks
10000
1111
********
ab: 0010
ba: 0111


C:\Users\Michel_GPC\AppData\Local\Temp\ipykernel_20304\577743432.py:17: DeprecationWarning: Insufficient bit width provided. This behavior will raise an error in the future.
  print("Masks", np.binary_repr(mask_a, width=nb),np.binary_repr(mask_b, width=nb),sep='\n' )


In [159]:
a = 7
b = 2
valor_de_alla = 1
m=4-valor_de_alla
mask_a= (-1 << m)
mask_b= ~(-1 << m) 

ab = (a & mask_a) | (b & mask_b) 
ba = (b & mask_a) | (a & mask_b)


int_to_bin = lambda x: print( np.binary_repr( x  , width=4) ) 

print("----Papas----")
int_to_bin(a)
int_to_bin(b)
print("----Hijos----")
int_to_bin(ab)
int_to_bin(ba)
print(ab,ba)

----Papas----
0111
0010
----Hijos----
0010
0111
2 7


In [145]:
a = np.array( [7,2,10])
b = np.array( [2,7,9])
m=1
mask_a= (-1 << m)
mask_b= ~(-1 << m) 

ab = (a & mask_a) | (b & mask_b) 
ba = (b & mask_a) | (a & mask_b)


ab,ba

(array([ 6,  3, 11], dtype=int32), array([3, 6, 8], dtype=int32))

In [144]:
int_to_bin = lambda x: print( np.binary_repr( x  , width=4) ) 

print("----Papas----")
int_to_bin(a)
int_to_bin(b)
print("----Hijos----")
int_to_bin(ab)
int_to_bin(ba)
print(ab,ba)

----Papas----


TypeError: only integer scalar arrays can be converted to a scalar index

In [162]:
a = pop_a
b = pop_b
valor_de_alla = np.array([0.59,0.89,0.80])
np.array([1,1,1])
np.array([1, 2, 2])

m=n_bits-valor_de_alla

mask_a= (-1 << m)
mask_b= ~(-1 << m) 

ab = (a & mask_a) | (b & mask_b) 
ba = (b & mask_a) | (a & mask_b)

NameError: name 'pop_a' is not defined