In [1]:
l_sel= [[5, 0, 1], [4, 2, 1], [5, 1, 0], [1, 5, 4], [0, 1, 4], [2, 1, 0], [1, 5, 3], [3, 2, 5], [0, 5, 3], [0, 4, 5],
        [0, 2, 3], [4, 0, 3], [4, 3, 1], [5, 3, 4], [2, 4, 3], [0, 2, 3], [3, 4, 1], [4, 3, 5], [2, 4, 1], [2, 3, 1],
        [3, 1, 2], [2, 4, 0], [4, 0, 5], [4, 3, 2]]

l_rand= [0.59, 0.96, 0.64, 0.86, 0.44, 0.70, 0.78, 0.96, 0.67, 0.89, 0.46, 0.34, 0.24, 0.80, 0.77, 0.11, 0.91, 0.69,
         0.80, 0.50, 0.60, 0.18, 0.55, 0.39, 0.68, 0.21, 0.01, 0.91, 0.78, 0.35, 0.04, 0.49, 0.43, 0.13, 0.82, 0.66,
         0.40, 0.50, 0.93, 0.64, 0.75, 0.96, 0.13, 0.30, 0.63, 0.55, 0.46, 0.87, 0.03, 0.59, 0.87, 0.42, 0.34, 0.68,
         0.99, 0.32, 0.15, 0.69, 0.40, 0.49, 0.58, 0.48, 0.76, 0.22, 0.73, 0.50, 0.10, 0.21, 0.95, 0.64, 0.41, 0.13,
         0.69, 0.48, 0.41, 0.08, 0.34, 0.14, 0.62, 0.71, 0.01, 0.70, 0.05, 0.37, 0.96, 0.26, 0.58, 0.88, 0.95, 0.05,
         0.06, 0.51, 0.39, 0.61, 0.45, 0.42, 0.25, 0.69, 0.18, 0.66, 0.72, 0.33, 0.90, 0.78, 0.36, 0.37, 0.91, 0.15, ]

l_cross= [1, 2, 2, 1, 2, 2, 2, 1, 1, 1]

pop=[[0, 1, 0, 1], [1, 0, 1, 0], [0, 0, 0, 0], [0, 1, 0, 1], [1, 0, 0, 1], [0, 0, 0, 1]]

r_cross = 0.9
r_mut = 0.25

min_value = -1
max_value = 1

In [2]:
import numpy as np
f = lambda x: x**2

In [21]:
# Codigo para que funcione con su entrada

b = [0, 0, 0, 0]

popn = []
for elem in pop:
    popn.append(b+elem)
popn
pop_int8 = np.packbits(popn)
pop_int8 # -> [-1,1]

#pop_int8,len(pop_int8),np.random.randint(0,10,6)

array([ 5, 10,  0,  5,  9,  1], dtype=uint8)

In [22]:
def mapping(decimal_values,min_value=-1,max_value=1):
    n = 4 #bits
    return min_value + decimal_values*(max_value - min_value)/(2**n-1)

decoded_values = mapping(pop_int8)
decoded_values

array([-0.33333333,  0.33333333, -1.        , -0.33333333,  0.2       ,
       -0.86666667])

In [23]:
fitnesses = f(decoded_values)
fitnesses

array([0.11111111, 0.11111111, 1.        , 0.11111111, 0.04      ,
       0.75111111])

In [62]:
l_sel = [[5, 0, 1], [4, 2, 1], [5, 1, 0], [1, 5, 4], [0, 1, 4], [2, 1, 0], [1, 5, 3], [3, 2, 5], [0, 5, 3], [0, 4, 5], [0, 2, 3], [4, 0, 3], [4, 3, 1], [5, 3, 4], [2, 4, 3], [0, 2, 3], [3, 4, 1], [4, 3, 5], [2, 4, 1], [2, 3, 1], [3, 1, 2], [2, 4, 0], [4, 0, 5], [4, 3, 2]]

l_sel_tmp = np.array(l_sel[:6]) # np.random.randint(0,5,(6,3)) sustituir algun dia 
#l_sel_tmp = np.random.randint(0,5,(6,3))

tournaments = np.choose(l_sel_tmp,fitnesses )
tournaments

array([[0.75111111, 0.11111111, 0.11111111],
       [0.04      , 1.        , 0.11111111],
       [0.75111111, 0.11111111, 0.11111111],
       [0.11111111, 0.75111111, 0.04      ],
       [0.11111111, 0.11111111, 0.04      ],
       [1.        , 0.11111111, 0.11111111]])

In [63]:
min_value = tournaments.min(axis=1)
index_array_min_arg = tournaments.argmin(axis=1)

print(min_value)
print(index_array_min_arg)


[0.11111111 0.04       0.11111111 0.04       0.04       0.11111111]
[2 0 1 2 2 1]


In [64]:
for datos,ind in zip(l_sel_tmp,index_array_min_arg):
    print(datos[ind])

1
4
1
4
4
1


In [75]:
ind_pop_int8 = np.take_along_axis(l_sel_tmp,index_array_min_arg.reshape( (-1,1) ),axis=1).reshape( (-1) )
ind_pop_int8

array([1, 4, 1, 4, 4, 1])

In [77]:
pop_elegida = pop_int8[ind_pop_int8]
pop_elegida

array([10,  9, 10,  9,  9, 10], dtype=uint8)

In [84]:
pop_a = pop_elegida[0::2]
pop_b = pop_elegida[1::2]
pop_a,pop_b

(array([10, 10,  9], dtype=uint8), array([ 9,  9, 10], dtype=uint8))

In [86]:
l_cross= np.array([1, 2, 2, 1, 2, 2, 2, 1, 1, 1],dtype=np.uint8) # random number

l_rand= [0.59, 0.96, 0.64, 0.86, 0.44, 0.70, 0.78, 0.96, 0.67, 0.89, 0.46, 0.34, 0.24, 0.80, 0.77, 0.11, 0.91, 0.69,
         0.80, 0.50, 0.60, 0.18, 0.55, 0.39, 0.68, 0.21, 0.01, 0.91, 0.78, 0.35, 0.04, 0.49, 0.43, 0.13, 0.82, 0.66,
         0.40, 0.50, 0.93, 0.64, 0.75, 0.96, 0.13, 0.30, 0.63, 0.55, 0.46, 0.87, 0.03, 0.59, 0.87, 0.42, 0.34, 0.68,
         0.99, 0.32, 0.15, 0.69, 0.40, 0.49, 0.58, 0.48, 0.76, 0.22, 0.73, 0.50, 0.10, 0.21, 0.95, 0.64, 0.41, 0.13,
         0.69, 0.48, 0.41, 0.08, 0.34, 0.14, 0.62, 0.71, 0.01, 0.70, 0.05, 0.37, 0.96, 0.26, 0.58, 0.88, 0.95, 0.05,
         0.06, 0.51, 0.39, 0.61, 0.45, 0.42, 0.25, 0.69, 0.18, 0.66, 0.72, 0.33, 0.90, 0.78, 0.36, 0.37, 0.91, 0.15, ]

r_cross = 0.9
r_mut = 0.25