In [1]:
import numpy as np

In [2]:
a = 7
b = 2
np.binary_repr(a, width=4),np.binary_repr(b, width=4)

('0111', '0010')

In [3]:
print( np.binary_repr(a, width=4),np.binary_repr(b, width=4),sep='\n' )
print("-"*4)
print(np.binary_repr(a & b, width=4))
print(np.binary_repr(a | b, width=4))
print(np.binary_repr(a ^ b, width=4))
print("-"*4)
print(np.binary_repr(a & ~b, width=4))
print(np.binary_repr(~a & b, width=4))
print("-"*4)
print(np.binary_repr(a << 2 , width=8))
print(np.binary_repr(a << 4 , width=8))
print("-"*4)
print(np.binary_repr(a >> 2 , width=8))
print(np.binary_repr(a >> 4 , width=8))

0111
0010
----
0010
0111
0101
----
0101
0000
----
00011100
01110000
----
00000001
00000000


In [8]:
a = 7
b = 2
nb = 5

#valor_de_alla = 1
#m=nb-valor_de_alla
m = 4-0 
print( np.binary_repr(a, width=nb),np.binary_repr(b, width=nb),sep='\n' )
print("-"*4)

#print("Mask 12,3", np.binary_repr(12, width=nb),np.binary_repr(3, width=nb),sep='\n' )


mask_a= (-1 << m)
mask_b= ~(-1 << m) # ~mask_a

print("Masks", np.binary_repr(mask_a, width=nb),np.binary_repr(mask_b, width=nb),sep='\n' )


print("*"*8)
print ("ab:" ,np.binary_repr( (a & mask_a) | (b & mask_b)  , width=nb))
print ("ba:" ,np.binary_repr( (b & mask_a) | (a & mask_b)  , width=nb))

00111
00010
----
Masks
10000
01111
********
ab: 00010
ba: 00111


In [9]:
a = 7
b = 2
valor_de_alla = 1
m=4-valor_de_alla
mask_a= (-1 << m)
mask_b= ~(-1 << m) 

ab = (a & mask_a) | (b & mask_b) 
ba = (b & mask_a) | (a & mask_b)


int_to_bin = lambda x: print( np.binary_repr( x  , width=4) ) 

print("----Papas----")
int_to_bin(a)
int_to_bin(b)
print("----Hijos----")
int_to_bin(ab)
int_to_bin(ba)
print(ab,ba)

----Papas----
0111
0010
----Hijos----
0010
0111
2 7


In [23]:
n_bits = 4

a = np.array([10, 10,  9], dtype=np.uint8) #pop_a
b = np.array([ 9,  9, 10], dtype=np.uint8)  #pop_b

#np.array([0.59,0.89,0.80])
#np.array([1,1,1])
valor_de_alla = np.array([1, 2, 2])

m=n_bits-valor_de_alla

mask_a= (-1 << m)
mask_b= ~(-1 << m) 

ab = (a & mask_a) | (b & mask_b) 
ba = (b & mask_a) | (a & mask_b)

In [17]:
ab,ba

(array([ 9,  9, 10], dtype=int32), array([10, 10,  9], dtype=int32))

In [26]:
np.stack((ab,ba), axis = 1)

array([[ 9, 10],
       [ 9, 10],
       [10,  9]], dtype=int32)

In [20]:
np.stack((ab,ba), axis = 1).flatten()

array([ 9, 10,  9, 10, 10,  9], dtype=int32)

In [16]:
np.array( list( zip(ab,ba) ) )

array([[ 9, 10],
       [ 9, 10],
       [10,  9]], dtype=int32)

In [18]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c = np.stack((a,b), axis = 1)

print(c)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [19]:
c.flatten()

array([ 1,  6,  2,  7,  3,  8,  4,  9,  5, 10])